# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UADemo_01' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UADemo_01
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJExtension', '~> 3.0.13'
end
