# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UADemo_02_OPP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UADemo_02_OPP

pod 'MJExtension', '~> 3.0.13'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.1'
end
